import "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\prsht.idl";
import "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\mshtml.idl";
import "c:\program files (x86)\microsoft sdks\windows\v7.0a\include\dimm.idl";
import "c:\program files (x86)\microsoft sdks\windows\v7.0a\include\dispex.idl";
import "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\mshtmhst.idl";
import "c:\program files (x86)\microsoft sdks\windows\v7.0a\include\docobj.idl";
import "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\exdisp.idl";
import "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\objsafe.idl";
import "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\oledb.idl";
import "c:\program files (x86)\microsoft sdks\windows\v7.0a\include\transact.idl";

[
	object,
	uuid(59da3a5d-109d-41f3-afdc-711b5262c769),
	oleautomation,
	helpstring("IEvcSolver Interface"),
	pointer_default(unique)
] 
#line 30 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
interface IEvcSolver : IUnknown {
#line 33 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propput,helpstring("Sets the saturation constant per capacity")] HRESULT  SaturationPerCap([in] BSTR value);
#line 35 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Gets the selected saturation constant per capacity")] HRESULT  SaturationPerCap([out,retval] BSTR *value);
#line 37 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propput,helpstring("Sets the critical density per capacity")] HRESULT  CriticalDensPerCap([in] BSTR value);
#line 39 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Gets the selected critical density per capacity")] HRESULT  CriticalDensPerCap([out,retval] BSTR *value);
#line 41 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Lists discriptive attributes from the network dataset")] HRESULT  DiscriptiveAttributes([out,retval] BSTR **names);
#line 43 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Counts discriptive attributes from the network dataset")] HRESULT  DiscriptiveAttributesCount([out,retval] int *count);
#line 45 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propput,helpstring("Sets the selected capacity attribute index")] HRESULT  CapacityAttribute([in] int index);
#line 47 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Gets the selected caspacity attribute index")] HRESULT  CapacityAttribute([out,retval] int *index);
#line 49 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propput,helpstring("Sets the separable evacuee flag")] HRESULT  SeparableEvacuee([in] VARIANT_BOOL value);
#line 51 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Gets the separable evacuee flag")] HRESULT  SeparableEvacuee([out,retval] VARIANT_BOOL *value);
#line 53 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propput,helpstring("Sets the export edge stat flag")] HRESULT  ExportEdgeStat([in] VARIANT_BOOL value);
#line 55 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Gets the export edge stat flag")] HRESULT  ExportEdgeStat([out,retval] VARIANT_BOOL *value);
#line 57 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propput,helpstring("Sets the solver method")] HRESULT  SolverMethod([in] char value);
#line 59 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Gets the selected solver method")] HRESULT  SolverMethod([out,retval] char *value);
#line 61 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propput,helpstring("Sets the cost method")] HRESULT  TrafficModel([in] char value);
#line 63 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Gets the selected cost method")] HRESULT  TrafficModel([out,retval] char *value);
#line 65 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propput,helpstring("Sets the cost per safe zone density")] HRESULT  CostPerZoneDensity([in] BSTR value);
#line 67 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Gets the cost per safe zone density")] HRESULT  CostPerZoneDensity([out,retval] BSTR *value);
#line 69 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propput,helpstring("Sets the flocking simulation interval in minutes")] HRESULT  FlockingSimulationInterval([in] BSTR value);
#line 71 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Gets the flocking simulation interval in minutes")] HRESULT  FlockingSimulationInterval([out,retval] BSTR *value);
#line 73 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propput,helpstring("Sets the flocking snapshot interval in minutes")] HRESULT  FlockingSnapInterval([in] BSTR value);
#line 75 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Gets the flocking snapshot interval in minutes")] HRESULT  FlockingSnapInterval([out,retval] BSTR *value);
#line 77 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propput,helpstring("Sets the flocking mode to on/off")] HRESULT  FlockingEnabled([in] VARIANT_BOOL value);
#line 79 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Gets the flocking mode")] HRESULT  FlockingEnabled([out,retval] VARIANT_BOOL *value);
#line 81 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propput,helpstring("Sets the two-way road capacity sharing")] HRESULT  TwoWayShareCapacity([in] VARIANT_BOOL value);
#line 83 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Gets the two way road capacity sharing")] HRESULT  TwoWayShareCapacity([out,retval] VARIANT_BOOL *value);
#line 85 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propput,helpstring("Sets the initial delay cost per population")] HRESULT  InitDelayCostPerPop([in] BSTR value);
#line 87 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Gets the initial delay cost per population")] HRESULT  InitDelayCostPerPop([out,retval] BSTR *value);
#line 89 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propput,helpstring("Sets the flocking profile")] HRESULT  FlockingProfile([in] char value);
#line 91 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Gets the selected flocking profile")] HRESULT  FlockingProfile([out,retval] char *value);
#line 93 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propput,helpstring("Sets the size of the evacuee bucket")] HRESULT  EvacueeBucketSize([in] BSTR value);
#line 95 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Gets the size of the evacuee bucket")] HRESULT  EvacueeBucketSize([out,retval] BSTR *value);
#line 99 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propput,helpstring("Sets the selected cost attribute index")] HRESULT  CostAttribute([in] int index);
#line 101 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Gets the selected cost attribute index")] HRESULT  CostAttribute([out,retval] int *index);
#line 103 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Lists impedence attributes from the network dataset")] HRESULT  CostAttributes([out,retval] BSTR **names);
#line 105 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	[propget,helpstring("Counts impedence attributes from the network dataset")] HRESULT  CostAttributesCount([out,retval] int *count);
};


[ version(1.0), uuid(F25947D1-9C81-48A6-9BFF-CF9EB158FFD7), helpstring("CustomSolver 1.0 Type Library") ]
library CustomSolver
{
	importlib("stdole2.tlb");
	importlib("olepro32.dll");

	importlib("\Program Files (x86)\ArcGIS\Desktop10.1\com\esrinetworkanalyst.olb");
	[
		version(1.0),
		uuid(7b081f99-b691-46b1-b756-aa72868c8683),
		helpstring("EvcSolver Class")
	] 
#line 119 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolver.h"
	coclass EvcSolver {
		[default]	interface IEvcSolver;
	};

	[
		version(1.0),
		uuid(cd267b89-0144-4e7c-929e-bcd5d82f4c4d),
		helpstring("EvcSolverPropPage Class")
	] 
#line 29 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolverproppage.h"
	coclass EvcSolverPropPage {
		[default]	interface IUnknown;
	};

	[
		version(1.0),
		uuid(6e127557-b452-444d-ac96-3a96a40c4071),
		helpstring("EvcSolverSymbolizer Class")
	] 
#line 32 "c:\\dev\\cpp\\uscgisresearchlab\\arccasper\\src\\evcsolversymbolizer.h"
	coclass EvcSolverSymbolizer {
		[default]	interface INASymbolizer2;
	};

}

